defaults:
  - RLModule_3d
  - /actor: 3d_ac_unet

_target_: rl4seg3d.PPO_3d.PPO3D

clip_value: 0.05        # 从0.2降低到0.05 (更保守的策略更新，针对类别不平衡)
k_steps_per_batch: 4
entropy_coeff: 0.01     # 从0.15降低到0.01 (增加探索，减少过度自信)
divergence_coeff: 0.015
