# 使用简单的卷积网络替代UNet以避免skip connection问题
_target_: torch.nn.Sequential

_args_:
  - _target_: torch.nn.Conv3d
    in_channels: 1
    out_channels: 16
    kernel_size: [3, 3, 3]
    padding: [1, 1, 1]
  
  - _target_: torch.nn.InstanceNorm3d
    num_features: 16
  
  - _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  
  - _target_: torch.nn.Conv3d
    in_channels: 16
    out_channels: 32
    kernel_size: [3, 3, 3]
    padding: [1, 1, 1]
  
  - _target_: torch.nn.InstanceNorm3d
    num_features: 32
  
  - _target_: torch.nn.LeakyReLU
    negative_slope: 0.01
  
  - _target_: torch.nn.Conv3d
    in_channels: 32
    out_channels: 1
    kernel_size: [1, 1, 1]
